export const PROFILE = '/profile'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'
export const SHOP_ROUTE = '/'
export const ABOUT = '/about'
export const TARIFFS = '/tariffs'
export const PARTNERS = '/partners'
export const REVIEWS = '/reviews'
